### ISSUE TITLE
Couldn't make it work when app is killed [android]

### ISSUE THREAD

**Issue by SushilShrestha** [evollu/react-native-gcm#3]
I am working on push notification for my app. I followed instructions from documentation. The app notifies me when app is on background but not when app is killed. Am I missing something?

```
import GCM from 'react-native-gcm-push-notification'
import Notification from 'react-native-system-notification'

var notification = GCM.popInitialNotification()
if (notification) {
  var info = JSON.parse(notification.info)
  Notification.create({
    subject: info.subject,
    message: info.message
  })
  GCM.stopService()
} else {
  class App extends Component {
    componentDidMount () {
      GCM.addEventListener('register', function (data) {
        if (!data.error) {
          console.log('send gcm token to server', data.registrationToken)
        }
      })
      GCM.addEventListener('notification', function (notification){
        console.log('receive gcm notification', notification)
        var info = JSON.parse(notification.data.info)
        if (!GCM.isInForeground) {
          Notification.create({
            subject: info.subject,
            message: info.message
          })
        }
      })

      GCM.requestPermissions()
    }
    render () {
      return <App />
    }
  }

  AppRegistry.registerComponent('App', () => App)
}
```

**Comment by evollu** [comment]
sorry to take it so long to respond. I was working on fcm project.
are you passing notification payload or data payload? If you are passing data payload, gcm will not wake up when app is killed

**Comment by ghost** [comment]
This is probably the same issue I pointed out in commit comment. `popInitialNotification` just never returns a notification in Android, It would be nice to find the cause and fix it.

**Comment by evollu** [comment]
change new GcmPackge() to new GcmPackage(getIntent() in MainActivity.java
this should fix it

**Comment by ghost** [comment]
Will try. It would be great if this helped.

**Comment by ghost** [comment]
App shows error when I supply `getIntent()` into `new GcmPackage()`. Menu stops working and after a while, app crashes.
![screenshot_2016-06-06-19-07-14](https://cloud.githubusercontent.com/assets/222129/15830873/d105b82e-2c1a-11e6-9b97-ac3499692b0a.png)

**Comment by ghost** [comment]
It starts fine without `getIntent()`.

**Comment by evollu** [comment]
Sorry I don't have any project using this plugin now. Can you debug into `getConstants` function in GcmModule.java file?

**Comment by ghost** [comment]
I don't have clue how. I am not developing in Java, I am just doing PN project in WebStorm.

But here is report from fabric:

```
Fatal Exception: java.lang.RuntimeException: Failed to initialize bridge
       at com.facebook.react.bridge.CatalystInstanceImpl.<init>(CatalystInstanceImpl.java:103)
       at com.facebook.react.bridge.CatalystInstanceImpl.<init>(CatalystInstanceImpl.java:39)
       at com.facebook.react.bridge.CatalystInstanceImpl$Builder.build(CatalystInstanceImpl.java:551)
       at com.facebook.react.ReactInstanceManagerImpl.createReactContext(ReactInstanceManagerImpl.java:867)
       at com.facebook.react.ReactInstanceManagerImpl.access$700(ReactInstanceManagerImpl.java:102)
       at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:198)
       at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:181)
       at android.os.AsyncTask$2.call(AsyncTask.java:287)
       at java.util.concurrent.FutureTask.run(FutureTask.java:234)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:838)
Caused by java.util.concurrent.ExecutionException: java.lang.NullPointerException
       at com.facebook.react.common.futures.SimpleSettableFuture.get(SimpleSettableFuture.java:68)
       at com.facebook.react.bridge.CatalystInstanceImpl.<init>(CatalystInstanceImpl.java:90)
       at com.facebook.react.bridge.CatalystInstanceImpl.<init>(CatalystInstanceImpl.java:39)
       at com.facebook.react.bridge.CatalystInstanceImpl$Builder.build(CatalystInstanceImpl.java:551)
       at com.facebook.react.ReactInstanceManagerImpl.createReactContext(ReactInstanceManagerImpl.java:867)
       at com.facebook.react.ReactInstanceManagerImpl.access$700(ReactInstanceManagerImpl.java:102)
       at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:198)
       at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:181)
       at android.os.AsyncTask$2.call(AsyncTask.java:287)
       at java.util.concurrent.FutureTask.run(FutureTask.java:234)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:838)
Caused by java.lang.NullPointerException
       at com.oney.gcm.GcmModule.convertJSON(GcmModule.java:118)
       at com.oney.gcm.GcmModule.getConstants(GcmModule.java:76)
       at com.facebook.react.bridge.BaseJavaModule.writeConstantsField(BaseJavaModule.java:441)
       at com.facebook.react.bridge.NativeModuleRegistry.writeModuleDescriptions(NativeModuleRegistry.java:82)
       at com.facebook.react.bridge.CatalystInstanceImpl.buildModulesConfigJSONProperty(CatalystInstanceImpl.java:368)
       at com.facebook.react.bridge.CatalystInstanceImpl.initializeBridge(CatalystInstanceImpl.java:127)
       at com.facebook.react.bridge.CatalystInstanceImpl.access$200(CatalystInstanceImpl.java:39)
       at com.facebook.react.bridge.CatalystInstanceImpl$1.call(CatalystInstanceImpl.java:96)
       at com.facebook.react.bridge.CatalystInstanceImpl$1.call(CatalystInstanceImpl.java:91)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$1.run(MessageQueueThreadImpl.java:73)
       at android.os.Handler.handleCallback(Handler.java:725)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:153)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:187)
       at java.lang.Thread.run(Thread.java:838)
```

**Comment by evollu** [comment]
at com.oney.gcm.GcmModule.convertJSON(GcmModule.java:118)

so here is the issue. seems like something null is passed into the function

**Comment by evollu** [comment]
try this:
in `GcmModule.java` file
change `Bundle bundle = mIntent.getBundleExtra("bundle");` in line 75 to 
`Bundle bundle = mIntent.getExtras();`

**Comment by evollu** [comment]
I use Android Studio to debug native code and it is convenient and has better logging

**Comment by ghost** [comment]
Yeah, that much I could conclude as well (I mean, the `null`). ;-)

This happens at the normal start of the app. IIRC you have added the JSON parsing into Java part and it wasn't there before. I think the problem is that with plain start of the app, there is no initial notification (and therefore, null). Maybe it should be `if`ed properly to distiguish between normal start and start driven by offline notification arriving.

Working on something else, but will see at it later.

**Comment by evollu** [comment]
good catch!
you can use `mIntent.getAction().equals("android.intent.action.MAIN")` to check if it is normal start up

**Comment by evollu** [comment]
another solution is checking if `mIntent.getBundleExtra("bundle")` is null. I think this makes more sense here. Can you verify if "click_action" is passed into the bundle when you receive notification?

**Comment by ghost** [comment]
I changed the appropriate part to:

``` java
        if (mIntent != null) {
            Bundle bundle = mIntent.getBundleExtra("bundle");
            if (bundle != null) {
                String bundleString = convertJSON(bundle);
                Log.d(TAG, "bundleString: " + bundleString);
                constants.put("initialNotification", bundleString);
            }
        }
```

but the problem is that I cannot get any events in the app itself. Because of this in `GcmModule` constructor:

``` java
        if (mIntent == null) {
            listenGcmRegistration();
            listenGcmReceiveNotification();
            getReactApplicationContext().addLifecycleEventListener(this);
        }
```

I presume it all needs a bit of redesign,

**Comment by ghost** [comment]
That is, I think every `mIntent` check should discriminate not between null / non-null case but between "non-null _and_ started because of offline notification" / "other". It is probably possible as I presume intent is different (and hopefully known) for the case of offline notification, and all the rest should be treated as standard startup.

**Comment by evollu** [comment]
you don't get any events because `mIntent.getBundleExtra("bundle")` is always null.
Here is working code for my fcm project. firebase cloud messaging is mento replace GCM. any reason you can't upgrade to newer google play service?

```
Map<String, Object> constants = new HashMap<>();
        if (mIntent != null) {
            if(mIntent.getExtras() != null) {
                Map<String, Object> extra = new HashMap<>();
                Bundle data = mIntent.getExtras();
                Set<String> keysIterator = data.keySet();
                for(String key: keysIterator){
                    extra.put(key, data.get(key));
                }
                constants.put("initialData", extra);
            }
            constants.put("initialAction", mIntent.getAction());
        }
        return constants;
```

**Comment by ghost** [comment]
I'm not getting any action because `listenGcmRegistration();` was not called because I pass non-null `mIntent`. That thing needs redesign, isn't it? Now you either give me initialNotification but not giving me registration and subsequent ones, or the other way - I don't get initial one but get all the others.

**Comment by ghost** [comment]
Are you sure that your above code is able to get _both_ inital notification, device id registration and subsequent push notification while app is live? Because that's what is not working - getting both. Now the `if (mIntent == null)` I posted above rules one of it out.

**Comment by ghost** [comment]
Unless I do not understand something and `getIntent()` returns `null` in normal appo startup, but it does not seem to be the case.

**Comment by evollu** [comment]
if you start app normally, getIntent() with return an Intent with `getAction() == "android.xxxx.DEFAULT"`. It will never be null

**Comment by evollu** [comment]
the code above is just for inital notification. It is RN's getContants method. `device id registration and subsequent push notification while app is live` is handled correctly by this library.

**Comment by ghost** [comment]
But again, if I pass `getIntent()` (which is not null), the registrations is not working. Because of `if` in the constructor.
Shouldn't both be working at the same time?

**Comment by evollu** [comment]
oh man, the code needs so much refactoring... Are you sure you can't upgrade to firebase cloud messaging?

**Comment by ghost** [comment]
(that is, not at the same time, but, pls:
- if I pass `getIntent()`, the registration and notification receiving is _not_ started;
- if I start app normally, that means it won't get registration nor notifications,
- I would like app, when _normally_ started, to receive registrations and notifications
- so, could it be made, somehow, that even I `getIntent()` is passed, the registration and notification is still received?)

FCM is part of firebase3, which is not working with RN.

**Comment by ghost** [comment]
What I was suggesting, `mIntent` test should not check for null, but somehow otherwise to distiguish "started because offline notification" versus "started normally / null passed".

**Comment by evollu** [comment]
fcm is working for RN. It is GCM with another name. Check https://github.com/evollu/react-native-fcm.
I'm keeping the null check in case someone doesn't need initial notification and initiates the package without getIntent().

**Comment by ghost** [comment]
That's what I was suggesting, keep the null check but you need add smarter check to it:

Discriminate between two cases:
1. null or normal start w/ getIntent() (listen to reg and notif)
2. getIntent w/ offline notification (do not listen)

Now it discriminates between:
1. null (listen to reg and notif)
2. normal start w/ getIntent() or getIntent w/ offline notification (do not listen)

The "normal start w/ getIntent()" ending up with "do not listen" is incorrect.

Libin Lu wrote:

**Comment by evollu** [comment]
agreed. let me work on it later today or tomorrow and try to fix the code

**Comment by ghost** [comment]
BTW thanks for pointing to fcm working in RN, I had the impression it is part of firebase3, which is not RN compatible yet.

**Comment by evollu** [comment]
if you decide to use FCM, I will drop support for this library. It is just an headache to maintain an outdated library and code not written by me

**Comment by ghost** [comment]
Will look if it is usable tomorrow.

**Comment by evollu** [comment]
cool. I will wait for your updates then

**Comment by aymericbouzy** [comment]
Hi, I'm running into the same problem. From what I see in FCM repository, there seems to be a lot of issues to solve still. Is there a partial fix at least for the time being?

**Comment by evollu** [comment]
issues in FCM is mostly configuration issue and use questions
have you tried it?

**Comment by aymericbouzy** [comment]
not yet. I am going to, I'll keep you posted

**Comment by aymericbouzy** [comment]
From the documentation, it sounds like FCM does not support notifications sent when app is killed : is that really the case? If so, there's no point for me to switch just yet.

**Comment by evollu** [comment]
it should support as FCM runs on the same framework as GCM
can you share the reference that it doesn't support?

**Comment by aymericbouzy** [comment]
I meant from the `react-native-fcm` repo : 
https://github.com/evollu/react-native-fcm#i-cant-get-notification-when-app-is-killed

**Comment by evollu** [comment]
oh, if you want to show banner when app is killed/ in background, you should always use `notification` payload instead of `data` payload. It is exact same behavior as GCM.

**Comment by aymericbouzy** [comment]
Ok thanks, I will try this. May I suggest you to create a gitter chat room for this repository ? I'm sure it would make things easier for this type of conversation.

**Comment by evollu** [comment]
gitter chat created for fcm repo

**Comment by aymericbouzy** [comment]
thanks!
